### ISSUE TITLE
beta-6 broke docker builds

### ISSUE THREAD

**Issue by acim** [drone-runners/drone-runner-kube#45]
```txt
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

I reverted image to beta-5 and it worked. I am using official Helm chart.

**Comment by bradrydzewski** [comment]
as of beta.6 you can no longer mount volumes into the docker plugin step (including ecr and gcr steps).  There are also some restricted environment variables.  Let;s move this to our support forum at discourse.drone.io.  If we determine this is in fact an issue, we can re-open this issue once we have enough details to reproduce.

**Comment by acim** [comment]
Yes, it worked without the volume, thank you.
